apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: app-node
          image: ricardocosta94/app-node:latest
          ports:
            - containerPort: 3000